name             'matt-vim'
maintainer       'Matt Chun-Lum'
maintainer_email 'mchunlum@gmail.com'
license          'all_rights'
description      'Installs/Configures matt-vim'
long_description 'Installs/Configures matt-vim'
version          '0.1.0'

depends 'apt'
depends 'git'
depends 'mercurial'
depends 'build-essential'
